pool:
  vmImage: 'windows-latest'  # Certifique-se de usar um agente Windows

steps:
# Restaurar pacotes NuGet
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/TestePortalIdsf.sln' # Caminho para o arquivo .sln

# Compilar o projeto usando MSBuild
- task: VSBuild@1
  inputs:
    solution: '**/*.sln'  # Altere para o caminho do seu .csproj se não houver um .sln
    msbuildArgs: '/p:Configuration=Release'
    platform: 'Any CPU'
    configuration: 'Release'

# Publicar artefatos
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
